// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJM9sRIm6Vgu5Fw9mTYs-NPqebd3M-d6E',
    appId: '1:1051848786143:web:7a33af17db7b3e3b93296a',
    messagingSenderId: '1051848786143',
    projectId: 'posapp-d4436',
    authDomain: 'posapp-d4436.firebaseapp.com',
    storageBucket: 'posapp-d4436.firebasestorage.app',
    measurementId: 'G-GCQHK0NE67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCURwKwK8Iyh_RNzOt18rQeqqef_J5n1tk',
    appId: '1:1051848786143:android:c4ba384c6501f48d93296a',
    messagingSenderId: '1051848786143',
    projectId: 'posapp-d4436',
    storageBucket: 'posapp-d4436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR_9TMdH9Hw7JZNjC0Yr1NpjbnWOKwGpA',
    appId: '1:1051848786143:ios:2c6fc4ef9f7893d693296a',
    messagingSenderId: '1051848786143',
    projectId: 'posapp-d4436',
    storageBucket: 'posapp-d4436.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR_9TMdH9Hw7JZNjC0Yr1NpjbnWOKwGpA',
    appId: '1:1051848786143:ios:2c6fc4ef9f7893d693296a',
    messagingSenderId: '1051848786143',
    projectId: 'posapp-d4436',
    storageBucket: 'posapp-d4436.firebasestorage.app',
    iosBundleId: 'com.example.posApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJM9sRIm6Vgu5Fw9mTYs-NPqebd3M-d6E',
    appId: '1:1051848786143:web:64b3609954b2316d93296a',
    messagingSenderId: '1051848786143',
    projectId: 'posapp-d4436',
    authDomain: 'posapp-d4436.firebaseapp.com',
    storageBucket: 'posapp-d4436.firebasestorage.app',
    measurementId: 'G-VBQ2MJD86X',
  );

}