// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYpNqVtlk9n6LZAmeudnpyrJjZ5Lm848A',
    appId: '1:629071960596:web:34e1b8e3981b514293e501',
    messagingSenderId: '629071960596',
    projectId: 'worldclock-118f7',
    authDomain: 'worldclock-118f7.firebaseapp.com',
    storageBucket: 'worldclock-118f7.firebasestorage.app',
    measurementId: 'G-F61BLFSLQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSCJOOXFLASSlOwXTLc6hwGfx6r5TeroM',
    appId: '1:629071960596:android:788c46ed7e83442693e501',
    messagingSenderId: '629071960596',
    projectId: 'worldclock-118f7',
    storageBucket: 'worldclock-118f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHhUT9ktKcivygHTRPzj4nXycIhHx3WMg',
    appId: '1:629071960596:ios:bc2627523c77c1ec93e501',
    messagingSenderId: '629071960596',
    projectId: 'worldclock-118f7',
    storageBucket: 'worldclock-118f7.firebasestorage.app',
    iosBundleId: 'com.example.worldClockCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHhUT9ktKcivygHTRPzj4nXycIhHx3WMg',
    appId: '1:629071960596:ios:bc2627523c77c1ec93e501',
    messagingSenderId: '629071960596',
    projectId: 'worldclock-118f7',
    storageBucket: 'worldclock-118f7.firebasestorage.app',
    iosBundleId: 'com.example.worldClockCase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYpNqVtlk9n6LZAmeudnpyrJjZ5Lm848A',
    appId: '1:629071960596:web:5eb71dad4d49fb0f93e501',
    messagingSenderId: '629071960596',
    projectId: 'worldclock-118f7',
    authDomain: 'worldclock-118f7.firebaseapp.com',
    storageBucket: 'worldclock-118f7.firebasestorage.app',
    measurementId: 'G-SK54ZZK80N',
  );
}
